version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: kanban
    volumes:
      - postgres-data:/var/lib/postgresql/data

  back:
    build:
      context: ./BACKEND
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: kanban
      DB_USER: postgres
      DB_PASSWORD: example
    ports:
      - '5000:5000'
    depends_on:
      - db

  front:
    build:
      context: ./FRONTEND
      dockerfile: Dockerfile
    ports:
      - '3000:3000'

volumes:
  postgres-data:
